- name: install services
  hosts: web
  gather_facts: false

  tasks:
  - name: install httpd service
    yum:
      name: httpd
      state: latest
  
  - name: start httpd service
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: httpd

  - name: make simple html page and ensure it is worked
    shell: echo "<h1> hello $(hostname -f) </h1>" > /var/www/html/index.html